name: simulator_echo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - matplotlib=3.10.0
  - tqdm=4.67.1
  - transformers=4.48.1
  - xgboost=2.1.0
  - pandas=2.2.3
  - pip:
      - asttokens==3.0.0
      - attrs==25.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.55.6
      - fsspec==2024.12.0
      - huggingface-hub==0.27.1
      - ipython==8.12.3
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter_client==8.6.3
      - jupyter_core==5.7.2
      - jupyterlab_pygments==0.3.0
      - kiwisolver==1.4.8
      - matplotlib-inline==0.1.7
      - mistune==3.1.1
      - mkl-service==2.4.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - prompt_toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - Pygments==2.19.1
      - pyparsing==3.2.1
      - pyzmq==26.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rpds-py==0.22.3
      - safetensors==0.5.2
      - soupsieve==2.6
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tornado==6.4.2
      - traitlets==5.14.3
      - triton==3.0.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - wheel==0.45.1
      - yarg==0.1.9
      - openpyxl == 3.1.5